-- +micrate Up
-- SQL in section 'Up' is executed when this migration is applied

CREATE SCHEMA IF NOT EXISTS orderman;

CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DELIVERY_ADDRESS (
    ID BIGSERIAL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ADDRESS1 VARCHAR(255) NOT NULL,
    ADDRESS2 VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    ZIP VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE IF NOT EXISTS INVOICE (
    ID BIGSERIAL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    INVOICE_NUMBER VARCHAR(255) NOT NULL,
    INVOICE_STATUS VARCHAR(255) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    TAX DECIMAL(10,2) NOT NULL,
    TOTAL DECIMAL(10,2) NOT NULL,
    PAYMENT_METHOD VARCHAR(255) NOT NULL,
    PAYMENT_STATUS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ID BIGSERIAL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    DELIVERY_ADDRESS_ID BIGINT NOT NULL,
    ORDER_NUMBER VARCHAR(255) NOT NULL,
    ORDER_STATUS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (DELIVERY_ADDRESS_ID) REFERENCES DELIVERY_ADDRESS(ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    SOLD_BY VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    ID BIGSERIAL PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

-- +micrate Down
-- SQL section 'Down' is executed when this migration is rolled back

DROP TABLE IF EXISTS ORDER_ITEM;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS DELIVERY_ADDRESS;
DROP TABLE IF EXISTS CUSTOMER;
DROP SCHEMA IF EXISTS orderman;
