version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: orderman
      POSTGRES_USER: crystal
      POSTGRES_PASSWORD: password
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql
    ports:
      # The postgres database container is exposed on the host at port 6543 to
      # allow connecting directly to it with postgres clients. The port differs
      # from the postgres default to avoid conflict with existing postgres
      # servers.
      - 6543:5432

volumes:
  postgres_data:
